[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.5"
regex = "1.7.0"
reqwest = { version = "0.11.13", features = ["blocking", "cookies"] }
transpose = "0.2.2"
